services:
  backend:
    container_name: backend
    build: .
    command: >
      sh -c "
      alembic upgrade heads
      &&
      python3 infrastructure/main.py
      "
    env_file:
      - .env
    ports:
      - 127.0.0.1:${API_PORT:-8000}:${API_PORT:-8000}
    depends_on:
      database:
        condition: service_healthy

  database:
    container_name: database
    image: postgis/postgis:17-3.4
    restart: always
    env_file:
      - .env
    volumes:
      - data-db:/var/lib/postgressql/data/
    command: -p ${POSTGRES_PORT:-5432}
    ports:
      - 127.0.0.1:${POSTGRES_PORT:-5432}:${POSTGRES_PORT}

    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB} -p ${POSTGRES_PORT}" ]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  data-db: